packaging_format = 2

id = "wireguard"
name = "WireGuard"
description.en = "Fast and modern VPN server, including a configuration webapp"
description.fr = "Serveur VPN rapide et moderne, incluant une webapp pour le configurer"

version = "0.5.2~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://www.wireguard.com/"
code = "https://github.com/ngoduykhanh/wireguard-ui"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/ngoduykhanh/wireguard-ui/releases/download/v0.5.2/wireguard-ui-v0.5.2-linux-arm64.tar.gz"
        arm64.sha256 = "024eb6da74f450a0f2715cc233573b714fdba14dbf9fd229ed1479bbd4e83ea6"
        amd64.url = "https://github.com/ngoduykhanh/wireguard-ui/releases/download/v0.5.2/wireguard-ui-v0.5.2-linux-amd64.tar.gz"
        amd64.sha256 = "f1f13fbc548cd28bf41e9517ccb2e3564f4d9f893d174bfa20f7a61d18e954c5"
        armhf.url = "https://github.com/ngoduykhanh/wireguard-ui/releases/download/v0.5.2/wireguard-ui-v0.5.2-linux-arm.tar.gz"
        armhf.sha256 = "b15c8ff43d09fa1d63aa63aa185a8a5b9f4ece02ebf67e9aa5152888d4a6be6b"
        i386.url = "https://github.com/ngoduykhanh/wireguard-ui/releases/download/v0.5.2/wireguard-ui-v0.5.2-linux-386.tar.gz"
        i386.sha256 = "60e2f0005f60b01e10feb65941fa2ad6e919cde1d8004eaacca713a4cea0ee7d"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = ".*-arm64.tar.gz"
        autoupdate.asset.amd64 = ".*-amd64.tar.gz"
        autoupdate.asset.armhf = ".*-arm.tar.gz"
        autoupdate.asset.i386 = ".*-386.tar.gz"

    [resources.ports]
    main.default = 8096
    wg.default = 8095
    wg.exposed = "UDP"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    [resources.apt]
    packages = "wireguard"
